### ISSUE TITLE
Adding text to a discussion appears to cause app to hang after first entry

### ISSUE THREAD

**Issue by alahj** [djali-foundation/djali-client#11]
One the discussion page for a sale, if I add a sentence, the text appears in the discussion.  However, if I try to add another sentence, the app hangs for several minutes, and doesn't allow subsequent text to be added.  This makes it feel like the messaging app is broken.

**Comment by 24thsaint** [comment]
Issue is being resolved at PR https://github.com/djali-foundation/djali-client/pull/28

**Comment by 24thsaint** [comment]
Solved.
