### ISSUE TITLE
Feature request: Add an explanation for how coupons work

### ISSUE THREAD

**Issue by alahj** [djali-foundation/djali-client#39]
![Screen Shot 2019-09-06 at 9 43 36 PM](https://user-images.githubusercontent.com/53591309/64469919-775f3480-d0ef-11e9-96f0-aa1b705a075b.png)

**Comment by 24thsaint** [comment]
![image](https://user-images.githubusercontent.com/8315544/64609355-5fddbf80-d3ff-11e9-85e8-c077c51b2ab7.png)
