### ISSUE TITLE
Bug report:  Add field labels for the coupons page

### ISSUE THREAD

**Issue by alahj** [djali-foundation/djali-client#40]
![Screen Shot 2019-09-06 at 9 43 36 PM](https://user-images.githubusercontent.com/53591309/64469930-965dc680-d0ef-11e9-87ad-b678d7add317.png)

**Comment by sianlasaga** [comment]
![image](https://user-images.githubusercontent.com/35569322/64517397-d8bb1980-d322-11e9-9d82-1dba9e6de513.png)
