### ISSUE TITLE
Bug report:  "Request failed with status code 500" error message when trying to update tags.

### ISSUE THREAD

**Issue by alahj** [djali-foundation/djali-client#42]
![Screen Shot 2019-09-06 at 9 48 05 PM](https://user-images.githubusercontent.com/53591309/64469997-a4601700-d0f0-11e9-8784-cdc90dc8dd5e.png)
Got "Request failed with status code 500" when trying to update tags on a new listing.

**Comment by nokusukun** [comment]
Unable to replicate after multiple tries, can anyone please take a screenshot of the developer tools console the next time this happens and reopen this issue, as well? Thanks.
