### ISSUE TITLE
Feature Request:  On the moderator page, show a list of available moderators

### ISSUE THREAD

**Issue by alahj** [djali-foundation/djali-client#43]
1) Moderators should be able to list the kinds of services they would be able to moderate for
2) When adding a moderator, user should be able to see Moderators who handle that kind of service. 

![Screen Shot 2019-09-07 at 11 15 51 AM](https://user-images.githubusercontent.com/53591309/64478704-f3459500-d160-11e9-8408-4257158c26ef.png)

**Comment by 24thsaint** [comment]
Hello! :))
We transferred moderator setup in the settings page cause it takes too long to crawl the network if moderators are freshly crawled every new listings. So it goes like:

[1] Vendor sets up list of moderators in the settings.
[2] When creating listing, vendor searches through this predefined list.

**Comment by 24thsaint** [comment]
It seems like this lacks some sort of descriptions/instructions during listing creation...

**Comment by 24thsaint** [comment]
![image](https://user-images.githubusercontent.com/8315544/64609399-71bf6280-d3ff-11e9-8518-2b59523d5805.png)
