### ISSUE TITLE
Bug report:  Filters on sales listings don't seem to work

### ISSUE THREAD

**Issue by alahj** [djali-foundation/djali-client#46]
Suppose I want to see all "Fulfllled" orders.  When I check the "Fulfilled" box on the sales page, I expect that it will change to display only "Fulfilled" orders.  Yet nothing seems to happen.  clicking on the "Sort" button takes me back to the home page.

**Comment by 24thsaint** [comment]
Sorry @alahj , the filters on the transaction histories are not yet implemented.
It's currently connected with issue https://github.com/djali-foundation/djali-client/issues/10 still pending.

**Comment by alahj** [comment]
Okay, thanks!
