### ISSUE TITLE
Some occupational titles seem to be missing

### ISSUE THREAD

**Issue by alahj** [djali-foundation/djali-client#6]
For example, if you look at the occupational titles listed here:
http://www.ilo.org/public/english/bureau/stat/isco/docs/index08-draft.xlsx
...some of the titles include:
Abbess, 
...
Therapist, occupational 
Therapist, massage 
Yet it does not appear to be possible to assign oneself those occupational titles, nor search for them.

**Comment by 24thsaint** [comment]
Priority.
