### ISSUE TITLE
Add editing menu for Description fields

### ISSUE THREAD

**Issue by alahj** [djali-foundation/djali-client#67]
Problem:  users don't know what editing tools are available. 
Solution:  Add editing menu to description fields

![Screen Shot 2019-09-17 at 12 38 07 PM](https://user-images.githubusercontent.com/53591309/65073849-809a9d80-d948-11e9-9273-4bc4f628d291.png)

**Comment by 24thsaint** [comment]
Resolved in https://github.com/djali-foundation/djali-client/commit/b6e126cb42d56ac1307cfcefcf579c3729be8c15
