### ISSUE TITLE
Changing route from a profile to another profile doesn't redirect to the desired profile

### ISSUE THREAD

**Issue by sianlasaga** [djali-foundation/djali-client#70]
Changing routes from `/profile` to `/profile/{id}` or vice versa doesn't rerender the desired profile. However, reloading the page will work.

**Comment by 24thsaint** [comment]
Fixed in https://github.com/djali-foundation/djali-client/commit/4ecd8e97472c4c3d2a9e51d7010e8382ae6e0d12.
