### ISSUE TITLE
searching on "developer" does not pull up "developer, software" in the occupation search field

### ISSUE THREAD

**Issue by alahj** [djali-foundation/djali-client#85]
The last entry is "Developer, Negative". 
![Screen Shot 2019-09-25 at 9 30 11 PM](https://user-images.githubusercontent.com/53591309/65658266-d374f480-dfdb-11e9-87d0-70e67c3deab1.png)

**Comment by 24thsaint** [comment]
We currently limit the results to ~20 entries, sir, for performance reasons.

We are currently planning to infinite-scroll the component.
