### ISSUE TITLE
saving new skills causes error

### ISSUE THREAD

**Issue by alahj** [djali-foundation/djali-client#86]
When I go to to Profile > Skills, and try to add a new skill I get a Error saving:  Request failed with status code 500.   

![Screen Shot 2019-09-25 at 10 27 38 PM](https://user-images.githubusercontent.com/53591309/65660522-ce1ba800-dfe3-11e9-8348-9be32a0ae1ce.png)

**Comment by 24thsaint** [comment]
It seems like we were in the middle of restarting the node when this happened.
Cannot be replicated on normal use.

Reopen if it happens again for further investigation.
