### ISSUE TITLE
Add a description for what "Proof" means on Social Media page

### ISSUE THREAD

**Issue by alahj** [djali-foundation/djali-client#9]
It's unclear what "Proof" means on https://test.djali.org/settings/profile page.  Add a help text link explaining what it's for.

**Comment by sianlasaga** [comment]
@alahj I added a tooltip instead of a separate link for the explanation. If it is fine with you sir we will merge the pull request #13. 
![image](https://user-images.githubusercontent.com/35569322/62993617-c3b9aa80-be8a-11e9-8f7a-01cdfc25b586.png)
